#pragma once

#define RESUME_GAME_COMMAND 0x01
#define EXIT_GAME_COMMAND 0x02
#define EXIT_TO_MAIN_MENU_COMMAND 0x03
#define SAVE_GAME_COMMAND 0x04
#define RESET_PROGRESS_COMMAND 0x05
#define LOAD_LEVEL_COMMAND 0x06